[versions]

managed-neo4j = "4.4.10"
managed-neo4j-driver = "4.4.9"

# Micronaut
micronaut-docs = "2.0.0"

[libraries]

managed-neo4j-harness = { module = "org.neo4j.test:neo4j-harness", version.ref = "managed-neo4j" }
managed-neo4j-java-driver = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "managed-neo4j-driver" }
