[versions]
micronaut = "5.0.0-M26"
micronaut-test = "5.0.0-M3"
managed-neo4j-driver = "6.0.5"
micronaut-validation = "5.0.0-M2"
micronaut-grpc = "4.12.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-grpc = { module = "io.micronaut.grpc:micronaut-grpc-bom", version.ref = "micronaut-grpc" }
managed-neo4j-java-driver = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "managed-neo4j-driver" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
testcontainers-neo4j = { module = "org.testcontainers:testcontainers-neo4j" }
