[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.1"
micronaut-test = "4.0.0"
groovy = "4.0.13"
spock = "2.3-groovy-4.0"

managed-neo4j = "5.9.0"
managed-neo4j-driver = "5.10.0"

#neo4j-harness needs the javax apis at runtime
javax-annotation-api = "1.3.2"
javax-validation-api = "2.0.1.Final"

micronaut-validation = "4.0.1"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-neo4j-harness = { module = "org.neo4j.test:neo4j-harness", version.ref = "managed-neo4j" }
managed-neo4j-java-driver = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "managed-neo4j-driver" }

javax-annotation-api = {group = "javax.annotation", name = "javax.annotation-api", version.ref = "javax-annotation-api" }
javax-validation-api = {group = "javax.validation", name = "validation-api", version.ref = "javax-validation-api" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
