name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  build_matrix:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - name: "Test Shell Execution"
        shell: bash
        run: |
          echo "Test started"
          nativeTestTasks=$(./gradlew tasks --no-daemon --all | grep -w "nativeTest")
          echo $nativeTestTasks
