name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  build_matrix:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Matrix
        uses: micronaut-projects/github-actions/graalvm/build-matrix@parallel-native-tests
        id: build-matrix
        with:
          graalvm: 'latest'
          java: '17'
  build:
    needs: build_matrix
    if: ${{ github.repository != 'micronaut-projects/micronaut-project-template' && needs.build_matrix.outputs.matrix.native_test_task }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Pre-Build Steps
        uses: micronaut-projects/github-actions/graalvm/pre-build@master
        id: pre-build
        with:
          graalvm: ${{ matrix.graalvm }}
          java: ${{ matrix.java }}
      - name: Build Steps
        uses: micronaut-projects/github-actions/graalvm/build@parallel-native-tests
        id: build
        env:
          GH_TOKEN_PUBLIC_REPOS_READONLY: ${{ secrets.GH_TOKEN_PUBLIC_REPOS_READONLY }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        with:
          nativeTestTask: ${{ matrix.native_test_task }}
      - name: Post-Build Steps
        uses: micronaut-projects/github-actions/graalvm/post-build@master
        id: post-build
        with:
          java: ${{ matrix.java }}
