name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  build_matrix:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup GraalVM CE"
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Set Matrix"
        shell: bash
        run: |
          gradleTasks = $(./gradlew tasks --no-daemon --all)
          echo $gradleTasks
