name: GraalVM Test Parallel
on:
  push:
    branches:
      - test-parallel-native
jobs:
  build_matrix:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Matrix
        uses: micronaut-projects/github-actions/graalvm/build-matrix@parallel-native-tests
        id: build-matrix
        with:
          graalvm: 'latest'
          java: '17'
  build:
    if: github.repository != 'micronaut-projects/micronaut-project-template' && ${{ needs.build_matrix.outputs.run-native-tests }} == 'true'
    runs-on: ubuntu-latest
    needs: build_matrix
    strategy:
      max-parallel: 6
      matrix: ${{fromJson(needs.build_matrix.outputs.matrix)}}
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - name: "Test Shell Execution"
        shell: bash
        run: |
          echo "Test started"
          nativeTestTasks=$(./gradlew tasks --no-daemon --all | grep -w "nativeTest")
          echo $nativeTestTasks
